source 'https://rubygems.org' 

gem 'dm-core'
gem 'dm-aggregates'
gem 'dm-constraints'
gem 'dm-migrations'
gem 'dm-transactions'
gem 'dm-serializer'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'dm-types'
gem 'dm-mysql-adapter'
gem 'dm-noisy-failures'
gem 'sinatra'
gem 'sinatra-contrib'
